### ISSUE TITLE
Feature Request: Expose ability to set whitespace pattern for SimpleScanner.SkipWS()

### ISSUE THREAD

**Issue by wiiittttt** [prataprc/goparsec#24]
It seems like if you want to use the SimpleScanner, but override the default whitespace pattern, you need to copy all of the code for the scanner locally and change the pattern. It would be great if there was a simple way to change the pattern via the packages API (either a global variable, public struct member, etc.)

If there is currently a way to do this already, please let me know.

**Comment by prataprc** [comment]
@wiiittttt by whitespace pattern do you mean SkipWS() ? Sometime back, @leovailati added a function called SkipAny(). Can you check whether it is useful for you ?

**Comment by wiiittttt** [comment]
That is what I used to modify your code for SkipWS():

```
func (s *SimpleScanner) SkipWS() ([]byte, parsec.Scanner) {
    return s.SkipAny(`^([ \t\r\n]|--.*)+`)
}
```

but it required copying all of the code for SimpleScanner locally.

If something like:

```
var whitespacePattern = `^[ \t\r\n]+`

func (s *SimpleScanner) SetWSPattern(pattern string) {
    whitespacePattern = pattern
}
```

was added, copying the code would not be necessary.

**Comment by prataprc** [comment]
Please check this function:
https://github.com/prataprc/goparsec/blob/master/scanner.go#L40

IMO, looks like this is what you need. You can use SkipAny(pattern) where every you need SkipWS().

**Comment by wiiittttt** [comment]
Unless I'm misunderstanding, using SkipAny() would require writing my own Scanner. SimpleScanner already does everything I need other than using a different whitespace pattern.

**Comment by prataprc** [comment]
SkipAny is already part of SimpleScanner. You can just call SkipAny(`^([ \t\r\n]|--.*)+`) it should work. Note that SkipAny is exported like SkipWS().

If there is still misunderstanding, please reach out https://gitter.im/prataprc/goparsec

**Comment by prataprc** [comment]
For future reference:

Terminal parsers like String(), Token(), Atom(), OrdTokens() internally uses SkipWS(), where SkipWS() was previously assuming a fixed pattern for white-space. This PR #28 fixes the issue by exporting a method to configure  whitespace to desired pattern.
