### ISSUE TITLE
how to define recursive grammar?

### ISSUE THREAD

**Issue by tiancaiamao** [prataprc/goparsec#4]
```
var (
	UnaryExpr  = Ord(And(LPAREN, Expr, RPAREN))
	Expr       = Ord(UnaryExpr, BinaryExpr)
)
```

as you see, UnaryExpr and Expr refer to each other.
this library won't work because when we define UnaryExpr, Expr is still uninitialized.

**Comment by prataprc** [comment]
Please check the example under goparsec/expr/expr.go

In the grammar `prod` is defined by `value` which is defined by `expr` which is  defined by `sum` which in turn is defined by `prod`.

The trick is,

pre-declare the combinator in heap/global, pass its reference to compose new combinators and finally compose and initialize the pre-declared combinator.

Let me know if it doesn't solve your problem.

Thanks,

**Comment by tiancaiamao** [comment]
oh, I see.  `doParse` is really tricky... 
thanks.
