### ISSUE TITLE
How to write parser to extract elements from an array

### ISSUE THREAD

**Issue by agnivade** [prataprc/goparsec#5]
Hi,

I am writing a service where I have to parse a array of bytes. Now, different portions of the array contain different fields which I need to extract. I am wondering if parser-combinator is a good candidate to approach this.

For eg- if I have array of 10 elements. 1-5 signify field1, 6-7 is field2, 8-10 is field3. And I want to pass the array and get those 3 fields. How would I do it using this library ?

P.S. - Sorry if this is a n00b question. I am trying with familiarize myself with the concept.

Thanks !

**Comment by tompaton** [comment]
That sounds a little too structured to bother with a parser - you can just slice out the bytes for each field if they are always the same size.

A parser is useful when the fields vary (in size, order) or are complex (have sub-fields).

See the example parsers for parsing json and arithmetical expressions for some ideas.

**Comment by agnivade** [comment]
Yep, agree. I have found [kaitai-struct](http://kaitai.io/) to be a good choice for this. 

Closing this.

**Comment by prataprc** [comment]
Agree with @tompaton.

IMHO erlang's [bit-syntax](http://erlang.org/doc/programming_examples/bit_syntax.html) is by far the best and concise way to parse binary streams. But the ease of use and its conciseness come from erlang's pattern matching feature.

A quick web-search gave some pointer for [python]( http://stackoverflow.com/questions/24852170/do-any-other-languages-support-bitstrings-other-than-erlang)

my 2 cents,
